import React, { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { useGameStore } from '../store/gameStore'
import { mockAPI } from '../lib/api'

/**
 * Enhanced Provably Fair Page
 * Shows house edge, verification tools, and detailed fairness information
 */
export const EnhancedProvablyFairPage: React.FC = () => {
  const {
    serverSeed,
    clientSeed,
    nonce,
    houseEdge,
    gameHistory,
    verifyRoll,
    generateNewSeeds,
  } = useGameStore()

  const [verificationResult, setVerificationResult] = useState<{
    isValid: boolean
    message: string
  } | null>(null)
  const [houseEdgeInfo, setHouseEdgeInfo] = useState<any>(null)

  useEffect(() => {
    // Get house edge information
    const info = mockAPI.getHouseEdgeInfo()
    setHouseEdgeInfo(info)
  }, [])

  const handleVerifyRoll = (hash: string) => {
    const isValid = verifyRoll(hash)
    setVerificationResult({
      isValid,
      message: isValid
        ? '✅ Roll is valid and provably fair!'
        : '❌ Roll verification failed!',
    })
  }

  const generateNewSeedsHandler = () => {
    generateNewSeeds()
    setVerificationResult(null)
  }

  const getVIPTierColor = (tier: string) => {
    switch (tier) {
      case 'Diamond':
        return 'from-purple-500 to-pink-500'
      case 'Gold':
        return 'from-yellow-400 to-yellow-600'
      case 'Silver':
        return 'from-gray-300 to-gray-500'
      default:
        return 'from-orange-400 to-orange-600'
    }
  }

  return (
    <div className="min-h-screen bg-hilo-black text-white p-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold text-hilo-gold mb-4">
            Provably Fair Gaming
          </h1>
          <p className="text-xl text-gray-300 max-w-2xl mx-auto">
            Complete transparency in every roll. Verify the fairness of our
            games using cryptographic proofs.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* House Edge Information */}
          <motion.div
            className="bg-gray-900 rounded-lg p-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
          >
            <h2 className="text-2xl font-bold text-hilo-gold mb-4">
              House Edge
            </h2>

            {houseEdgeInfo && (
              <div className="space-y-4">
                <div className="bg-gray-800 rounded-lg p-4">
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-gray-300">House Edge</span>
                    <span className="text-2xl font-bold text-hilo-red">
                      {(houseEdgeInfo.houseEdge * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-gray-300">Player Win Chance</span>
                    <span className="text-2xl font-bold text-hilo-green">
                      {(houseEdgeInfo.playerWinChance * 100).toFixed(1)}%
                    </span>
                  </div>
                </div>

                <p className="text-sm text-gray-400">
                  {houseEdgeInfo.explanation}
                </p>

                <div className="bg-hilo-gold/10 border border-hilo-gold rounded-lg p-4">
                  <h3 className="font-bold text-hilo-gold mb-2">
                    Why House Edge?
                  </h3>
                  <ul className="text-sm text-gray-300 space-y-1">
                    <li>• Ensures casino sustainability</li>
                    <li>• Covers operational costs</li>
                    <li>• Maintains fair gameplay</li>
                    <li>• Industry standard practice</li>
                  </ul>
                </div>
              </div>
            )}
          </motion.div>

          {/* Current Seeds */}
          <motion.div
            className="bg-gray-900 rounded-lg p-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
          >
            <h2 className="text-2xl font-bold text-hilo-gold mb-4">
              Current Seeds
            </h2>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Server Seed (Hash)
                </label>
                <div className="bg-gray-800 rounded-lg p-3 font-mono text-sm break-all">
                  {serverSeed}
                </div>
                <p className="text-xs text-gray-400 mt-1">
                  Generated by the server, revealed after each game
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Client Seed
                </label>
                <div className="bg-gray-800 rounded-lg p-3 font-mono text-sm break-all">
                  {clientSeed}
                </div>
                <p className="text-xs text-gray-400 mt-1">
                  You can change this to any value you want
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Nonce
                </label>
                <div className="bg-gray-800 rounded-lg p-3 font-mono text-sm">
                  {nonce}
                </div>
                <p className="text-xs text-gray-400 mt-1">
                  Increments with each roll
                </p>
              </div>

              <button
                onClick={generateNewSeedsHandler}
                className="w-full py-2 bg-hilo-gold text-black font-bold rounded-lg hover:bg-hilo-gold/80 transition-colors"
              >
                Generate New Seeds
              </button>
            </div>
          </motion.div>

          {/* Verification Tool */}
          <motion.div
            className="bg-gray-900 rounded-lg p-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
          >
            <h2 className="text-2xl font-bold text-hilo-gold mb-4">
              Verify Roll
            </h2>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Enter Hash to Verify
                </label>
                <input
                  type="text"
                  placeholder="Paste roll hash here..."
                  className="w-full px-3 py-2 bg-gray-800 border border-gray-600 rounded-lg text-white font-mono text-sm"
                  onKeyPress={e => {
                    if (e.key === 'Enter') {
                      handleVerifyRoll(e.currentTarget.value)
                    }
                  }}
                />
              </div>

              {verificationResult && (
                <motion.div
                  className={`p-4 rounded-lg ${
                    verificationResult.isValid
                      ? 'bg-green-900/50 border border-green-500'
                      : 'bg-red-900/50 border border-red-500'
                  }`}
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ type: 'spring', stiffness: 200 }}
                >
                  <div
                    className={`font-bold ${
                      verificationResult.isValid
                        ? 'text-green-400'
                        : 'text-red-400'
                    }`}
                  >
                    {verificationResult.message}
                  </div>
                </motion.div>
              )}

              <div className="bg-gray-800 rounded-lg p-4">
                <h3 className="font-bold text-white mb-2">How to Verify:</h3>
                <ol className="text-sm text-gray-300 space-y-1 list-decimal list-inside">
                  <li>Copy the hash from your game history</li>
                  <li>Paste it in the input field above</li>
                  <li>Click verify or press Enter</li>
                  <li>Check if the result matches your roll</li>
                </ol>
              </div>
            </div>
          </motion.div>

          {/* Recent Rolls */}
          <motion.div
            className="bg-gray-900 rounded-lg p-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
          >
            <h2 className="text-2xl font-bold text-hilo-gold mb-4">
              Recent Rolls
            </h2>

            <div className="space-y-2 max-h-64 overflow-y-auto">
              {gameHistory.slice(0, 10).map((game, index) => (
                <motion.div
                  key={game.id}
                  className="bg-gray-800 rounded-lg p-3 hover:bg-gray-700 transition-colors"
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1 }}
                >
                  <div className="flex justify-between items-start mb-2">
                    <div className="flex items-center gap-2">
                      <span
                        className={`text-lg ${
                          game.won ? 'text-hilo-green' : 'text-hilo-red'
                        }`}
                      >
                        {game.won ? '🎉' : '😞'}
                      </span>
                      <span className="font-bold">
                        {game.side.toUpperCase()} - {game.roll}
                      </span>
                    </div>
                    <span className="text-sm text-gray-400">
                      {game.timestamp.toLocaleTimeString()}
                    </span>
                  </div>

                  <div className="flex justify-between items-center text-sm">
                    <span className="text-gray-300">Bet: {game.bet} HILO</span>
                    <span className="text-gray-300">
                      Multiplier: {game.multiplier}x
                    </span>
                  </div>

                  <div className="mt-2">
                    <div className="text-xs text-gray-400 font-mono break-all">
                      Hash: {game.hash}
                    </div>
                    <button
                      onClick={() => handleVerifyRoll(game.hash)}
                      className="mt-1 text-xs text-hilo-gold hover:text-hilo-gold/80 transition-colors"
                    >
                      Verify this roll
                    </button>
                  </div>
                </motion.div>
              ))}

              {gameHistory.length === 0 && (
                <div className="text-center text-gray-400 py-8">
                  <div className="text-4xl mb-2">🎲</div>
                  <div>No games played yet</div>
                  <div className="text-sm">
                    Start playing to see your roll history
                  </div>
                </div>
              )}
            </div>
          </motion.div>
        </div>

        {/* Fairness Guarantee */}
        <motion.div
          className="mt-12 bg-gradient-to-r from-hilo-gold/10 to-hilo-red/10 border border-hilo-gold rounded-lg p-8 text-center"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
        >
          <h2 className="text-3xl font-bold text-hilo-gold mb-4">
            Fairness Guarantee
          </h2>
          <p className="text-lg text-gray-300 mb-6 max-w-3xl mx-auto">
            Every roll is cryptographically verifiable. We use industry-standard
            hashing algorithms to ensure complete transparency and fairness. You
            can verify any roll at any time.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-8">
            <div className="text-center">
              <div className="text-4xl mb-2">🔒</div>
              <h3 className="font-bold text-white mb-2">
                Cryptographically Secure
              </h3>
              <p className="text-sm text-gray-400">
                Uses SHA-256 hashing for maximum security
              </p>
            </div>

            <div className="text-center">
              <div className="text-4xl mb-2">👁️</div>
              <h3 className="font-bold text-white mb-2">Fully Transparent</h3>
              <p className="text-sm text-gray-400">
                All seeds and hashes are publicly visible
              </p>
            </div>

            <div className="text-center">
              <div className="text-4xl mb-2">✅</div>
              <h3 className="font-bold text-white mb-2">
                Independently Verifiable
              </h3>
              <p className="text-sm text-gray-400">
                Verify any roll using our open-source tools
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  )
}

export default EnhancedProvablyFairPage
